fetch_all_posts_task:
  description: >
    Search for all blog posts published with the URL {blog_url}.
    Save these posts to a CSV file.
  expected_output: >
    A string with the path of the CSV file.
  agent: content_analyzer

identify_posts_cannibalization_task:
  description: >
    Read the provided CSV file and analyze title, link and keyword to identify potential content cannibalization.
    Flag lines where similar content are found. Use your analytical skills to determine if posts are too similar.
    
    Also flag links that are not identical, but that could also be cannibalizing.
    For example:
      example 1: https://rafaelcarvalho.tv/area-de-pessoas-1/ and https://rafaelcarvalho.tv/area-de-mÃ£es/
      example 2: https://rafaelcarvalho.tv/afiliado/ and https://rafaelcarvalho.tv/afiliados/
  expected_output: >
    A list of flagged lines with potential content cannibalization.
    The list must be delivered by grouping the posts that were identified similar content as follows:

  # Cannibalization 01:
  # - post ID: title, link
  # - post ID: title, link

  # Cannibalization 02:
  # - post ID: title, link
  # - post ID: title, link
  agent: content_analyzer

# recommend_post_actions_task:
#   description: >
#     For each set of duplicate posts, recommend which ones to keep, delete, or merge.
#   expected_output: >
#     Actionable recommendations for each set of duplicate posts.
#   agent: content_analyzer

# suggest_new_keywords_task:
#   description: >
#     Analyze current keyword coverage and suggest new posts to cover important keywords not currently addressed.
#   expected_output: >
#     A list of new post topics with suggested keywords.
#   agent: seo_strategist

# merge_content_task:
#   description: >
#     Provide specific recommendations on how to merge duplicate posts into a single optimized post.
#   expected_output: >
#     Detailed merging guidelines for each set of duplicate posts.
#   agent: content_merger
